### ISSUE TITLE
Notes about building with podman

### ISSUE THREAD

**Issue by Missingmew** [robinchrist/ONIE-Adventures#1]
Followed your guide, found the following when using podman instead of docker:
- When entering the container, I had to use simply `--run` instead of `--run-image` because it wouldnt find the image prepared earlier. This didnt pose an issue since its the only image I had available (might cause some with more).
- The build took about 9 minutes for me on a Ryzen 9 5950x using `-j64`, `ONIE_HOME` was located on ramdisk.
- I noticed that major parts of the build process didnt actually run on more than a handful of cores, I assume that the bottleneck isnt the CPU but parts of the build itself.

Extra notes:
- Your snippet is missing a `git clone` in front of the `https://github.com/opencomputeproject/onie.git onie-build`
- The image names for due in the preparation and run snippets are different, is that intentional?

**Comment by robinchrist** [comment]
> * When entering the container, I had to use simply `--run` instead of `--run-image` because it wouldnt find the image prepared earlier. This didnt pose an issue since its the only image I had available (might cause some with more).
> * The build took about 9 minutes for me on a Ryzen 9 5950x using `-j64`, `ONIE_HOME` was located on ramdisk.

I added some notes to the README



> * Your snippet is missing a `git clone` in front of the `https://github.com/opencomputeproject/onie.git onie-build`

Fixed, thanks



> * The image names for due in the preparation and run snippets are different, is that intentional?

Yep.
```
robin@WS-DA-7773X:/data/dev/onie/DUE$ ./due -m --list-images
REPOSITORY   TAG         IMAGE ID       CREATED        SIZE
due-onie-build-debian-9      onie-9      799fa4456b25   5 hours ago    938MB
due-onie-build-debian-10     onie-10     a8c97fef9d32   5 hours ago    1.28GB
due-onie-build-debian-11     onie-11     5870d9200e11   5 hours ago    1.22GB
```

due prepends the `due-` prefix to the image name from `./due --create --platform linux/amd64 --name onie-build-debian-9`
